urls.py
from django.conf.urls.defaults import *
from django.contrib import admin
from django.conf import settings
from posts import views as posts_views
from posts.feeds import LatestEntriesFeed

admin.autodiscover()

site_feeds = {
    'all': LatestEntriesFeed,
}

urlpatterns = patterns('',
    (r'^admin/', include(admin.site.urls)),
    url(r'^$', posts_views.index, name='index'),
    url(r'^photo/(?P<slug>[\w-]+)(?P<year>[\d-]+)(?P<day>[\d-]+)(?P<month>[\d-]+)/$', posts_views.photo_detail, name='photo_detail'),
    # (r'^rss/$', LatestEntriesFeed()),
    (r'^rss/(?P<url>[\w]+)/$', 'django.contrib.syndication.views.Feed', {'feed_dict': site_feeds}),
    url(r'^(?P<slug>[\w-]+)/$', posts_views.post_detail, name='post-detail'),
    
)


if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', 
         { 'document_root' : settings.MEDIA_ROOT, 'show_indexes' : False })
    )

posts/models.py
from django.db import models
from posts.managers import PublicPostManager
from syncr.flickr.models import PhotoSet


class Post(models.Model):
    BROOKLYN = "brooklyn"
    BRONX = "bronx"
    STATENISLAND = "statenisland"
    QUEENS = "queens"
    MANHATTAN = "manhattan"
    BOROUGH_CHOICES = (
        (BROOKLYN, "Brooklyn"),
        (BRONX, "The Bronx"),
        (QUEENS, "Queens"),
        (STATENISLAND, "Staten Island"),
        (MANHATTAN, "Manhattan"),
    )
    
    title = models.CharField(max_length=255)
    subtitle = models.TextField(blank=True, null=True)
    slug = models.SlugField()
    photo_set = models.ForeignKey(PhotoSet)
    
    borough = models.CharField(max_length=50,
                               default=BROOKLYN,
                               choices=BOROUGH_CHOICES)
    coordinates = models.CharField(max_length=255, default="40.685935,-73.986214")
    zoom = models.IntegerField(default=15)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)
    publish_date = models.DateTimeField(auto_now_add=True)
    is_public = models.BooleanField(default=False)
    
    public = PublicPostManager()
    objects = models.Manager()
    
    def __unicode__(self):
        return "%s: %s (%s)" % (
            self.title,
            self.photo_set.title,
            self.publish_date,
        )
    
    @models.permalink
    def get_absolute_url(self):
        return ('post-detail', (), {'slug': self.slug})



class Callout(models.Model):
    DETAIL = 'detail'
    BACKGROUND = 'background'
    QUOTE = 'quote'
    LINK = 'link'
    CALLOUT_CHOICES = (
        (DETAIL, 'Detail'),
        (BACKGROUND, 'Background'),
        (QUOTE, 'Quote'),
        (LINK, 'Link'),
    )
    
    post = models.ForeignKey(Post)
    content = models.TextField(null=True, blank=True)
    content_type = models.CharField(max_length=50,
                                    default=BACKGROUND,
                                    choices=CALLOUT_CHOICES)
    order = models.IntegerField(default=1)
    date = models.DateTimeField(null=True, blank=True)
    link = models.TextField(null=True, blank=True)
    quote_speaker = models.CharField(max_length=255, null=True, blank=True)
    detail_image_url = models.URLField(null=True, blank=True)

    def __unicode__(self):
        return "[#%s] %s" % (
            self.order,
            self.post,
        )
        

templates/base.html
{% load compressed typogrify %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1" />
  <meta http-equiv="imagetoolbar" content="no" />
  <link rel="alternate" type="application/rss+xml" title="RSS" href="/rss/all/" /> 
  {% block meta %}{% endblock %}
  <title>{% block title %}New York Field Guide - Historic Districts of New York City{% endblock %}</title>
  <link rel="icon" href="/favicon.ico" />
  {% compressed_css 'global' %}
  {% compressed_js 'common' %}
    <script src="http://maps.google.com/maps?file=api&amp;v=2&amp;sensor=false&amp;key=ABQIAAAALPrVZ2XoxUkCpRj5Bx5pQhSpVo_X8WafOyOBej8hr_9Y8RYTuRR4F5aWTAPtDTsWBEr1CmPTdcA2iA" type="text/javascript"></script>
  {# <!--[if IE]>{% compressed_css 'ie_only' %}<![endif]--> #}
  {% block head %}{% endblock %}
</head>
<body>
  <div id="header" class="content">
    <div class="splash-header">
      <h1 class="splash-big"><a href="{% url "index" %}">New York <span class="highlight highlight-title">Field Guide</span></a></h1>
      <h3 class="splash-small">Historic Districts <span class="highlight highlight-title">of</span> New York City</h3>  
    </div>
  </div>

  <div id="content">
    {% block content %}{% endblock content %}
  </div>
  
  <div id="footer" class="content">
    <div class="footer-info">
      <b><a href="{% url "index" %}">New York <span class="highlight highlight-title">Field Guide</span></a></b> is curated and researched by <b><a href="http://www.samuelclay.com">Samuel Clay</a></b>.
    </div>
    <div class="footer-post photoset">
      {% block footer_post_borough %}{% endblock footer_post_borough %}
    </div>
    <div class="footer-post photoset last">
      {% block footer_post_elsewhere %}{% endblock footer_post_elsewhere %}
    </div>
  </div>
  <script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
try {
var pageTracker = _gat._getTracker("UA-15400459-1");
pageTracker._trackPageview();
} catch(err) {}</script>

</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load compressed typogrify post_tags %}

{% block content %}

{% filter typogrify %}
  <div id="splash">
    
      
      <ul class="posts photosets">
        {% for post in posts %}
          <li class="photoset content">
            
            <div class="photoset-borough">{{ post.get_borough_display }}</div>
          
            {% photoset_info post %}
          
            <div class="photoset-photos photo-thumbs">
              {% photo_thumbs post 4 12 %}
            </div>
          
            <div class="photoset-map-container">
              <script>
              $(document).ready(function() {
                    var map = new GMap2(document.getElementById("map_canvas_{{ forloop.counter }}")); 
                    var geoXml = new GGeoXml("http://maps.google.com/maps/ms?ie=UTF8&hl=en&msa=0&output=nl&msid=116208418513892880794.000480206e4027e04ae53");
                    map.addControl(new GSmallZoomControl3D());
                    map.setMapType(G_PHYSICAL_MAP);
                    map.setCenter(new GLatLng({{ post.coordinates }}), {{ post.zoom }}); 
                    map.addOverlay(geoXml);
              });
              </script>
              <div id="map_canvas_{{ forloop.counter }}" class="photoset-map"></div>
            </div>
          
          </li>
        {% endfor %}
      </ul>
  
  </div>

{% endfilter %}

{% endblock content %}

templates/photo_thumbs.html
{% for photo in photos %}
  <a href="{{ post.get_absolute_url }}"><img src="{{ photo.get_square_url }}" class="{% if forloop.counter0|divisibleby:per_row %}first{% endif %}{% if forloop.counter|divisibleby:per_row %}last{% endif %}" /></a>
{% endfor %}  

templates/photoset_info.html
{% load post_tags %}
            
<div class="photoset-info">
  <h2 class="photoset-title">
    {% filter highlight:'Historic District' %}
      <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    {% endfilter %}
  </h2>
  {% if not hide_subtitle %}<div class="photoset-subtitle">{{ post.subtitle }}</div>{% endif %}
  <div class="photoset-count"><span class="photoset-count-number">{{ post.photo_set.photos.count }}</span> photos</div>
</div>

templates/post-detail.html
{% extends 'base.html' %}
{% load compressed typogrify post_tags %}

{% block title %}{{ post.title }} - New York Field Guide{% endblock title %}

{% block content %}

{% filter typogrify %}
  <div class="photoset-detail">

    <div class="content">
      <div class="photoset-borough">{{ post.get_borough_display }}</div>
      {% photoset_info post %}
    </div>
    
    <ul class="photoset-photos">
    {% for photo in photos %}

      {% with forloop.counter as photo_order %}
      {% for callout in callouts %}{% ifequal callout.order photo_order %}
        <li class="callout">
          
          <div class="callout-content content">
            {% if callout.detail_image_url %}
              <div class="callout-image"><img src="{{ callout.detail_image_url}}" /></div>
            {% endif %}
            {% if callout.date %}
              <div class="callout-date">{{ callout.date|date:"F d"}}<span class="nth">{{ callout.date|date:"S" }}</span>, {{ callout.date|date:"Y" }}</div>
            {% endif %}
            <div class="callout-content">
              {{ callout.content|safe }}
            </div>
            {% if callout.link %}
              <div class="callout-link"><a href="{{ callout.link }}">{{ callout.link }}</a></div>
            {% endif %}
            {% if callout.quote_speaker %}
              <div class="callout-quote-speaker">{{ callout.quote_speaker }}</div>
            {% endif %}
          </div>
          
        </li>
      {% endifequal %}{% endfor %}
      {% endwith %}
      
      <li class="photo-detail content">
        <img src="{{ photo.get_large_url }}" />
        {% if photo.description and 'Part of New York Field Guide' not in photo.description %}
          <div class="photo-detail-description">{{ photo.description|safe }}</div>
        {% endif %}
        <a href="{{ photo.photopage_url }}" title="{{ photo.title }} at Flickr" class="photo-detail-date">{{ photo.taken_date|date:"F j, Y"}}</a>
        <a href="{{ photo.photopage_url }}" title="{{ photo.title }} at Flickr" class="photo-detail-exif">
          {{ photo.exif_make }} {{ photo.exif_model }} with {{ photo.exif_focal_length }} at <b>{{ photo.exif_aperture }}</b>, <b>ISO {{ photo.exif_iso }}</b>, {{ photo.exif_exposure }}
        </a>
      </li>
      
    {% endfor %}  
    </ul>
    
    <div class="content">
      <div class="photoset-map-container">
        <script>
        $(document).ready(function() {
              var map = new GMap2(document.getElementById("map_canvas_{{ forloop.counter }}")); 
              var geoXml = new GGeoXml("http://maps.google.com/maps/ms?ie=UTF8&hl=en&msa=0&output=nl&msid=116208418513892880794.000480206e4027e04ae53");
              map.addControl(new GSmallZoomControl3D());
              map.setMapType(G_PHYSICAL_MAP);
              map.setCenter(new GLatLng({{ post.coordinates }}), {{ post.zoom }}); 
              map.addOverlay(geoXml);
        });
        </script>
        <div id="map_canvas_{{ forloop.counter }}" class="photoset-map"></div>
      </div>
    </div>
    
  
  </div>

{% endfilter %}

{% endblock content %}

{% block footer_post_borough %}
  {% if footer_post_borough %}
    <div class="footer-post-subtitle">Elsewhere in {{ footer_post_borough.get_borough_display }}...</div>
    {% photoset_info footer_post_borough 1 %}
    <div class="footer-photos photo-thumbs">
      {% photo_thumbs footer_post_borough 4 8 %}
    </div>
  {% endif %}
{% endblock footer_post_borough %}

{% block footer_post_elsewhere %}
  {% if footer_post_elsewhere %}
    <div class="footer-post-subtitle">Elsewhere in New York City...</div>
    {% photoset_info footer_post_elsewhere 1 %}
    <div class="footer-photos photo-thumbs">
      {% photo_thumbs footer_post_elsewhere 4 8 %}
    </div>
  {% endif %}
{% endblock footer_post_elsewhere %}